<?php


namespace App\Command;


use App\Service\PowerpointDelete;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PurgePowerpointCommand extends Command
{
    protected static $defaultName = 'app:purge-powerpoint';

    protected function configure()
    {
        $this
            ->setDescription('Supprimer les powrpoints superieur a 10 minutes')
            ->addArgument('dirFolder', InputArgument::REQUIRED, 'Quel est le chemin vers le dossier a supprimer')
            ->addArgument('time', InputArgument::REQUIRED, 'Combien de minutes a supprimer')
        ;
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        //recupere l'url du dossier depuis commande console
        $dir = $input->getArgument('dirFolder');

        //Calcul de la date maximale de retarait
        $dateRetrait = strtotime("now".' - '.$input->getArgument('time').' minutes');

        foreach(scandir($dir) as $file)
        {
            if(!is_dir($file)) {
                $dateFile = filemtime($dir . '/' . $file);

                if ($dateFile < $dateRetrait) {
                    unlink($dir.'/'.$file);
                }

            }
        }

        return 0;
    }
}